name: My workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo "hello" > myfile.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: myfile.txt

  use-artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Read file
        run: cat myfile.txt