name: Inputs Choice Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  show-input:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Environment is ${{ github.event.inputs.environment }}"
