name: Secrets Demo

on:
  push:

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Secret length: ${#MY_SECRET}"
        env:
          MY_SECRET: ${{ secrets.SECRET_NAME }}
